### ISSUE TITLE
Switch to v2 (Wellbeing) API

### ISSUE THREAD

**Issue by Phype** [Ekman/home-assistant-pure-i9#22]
Since the purei app was shut down, i guess it would also a good idea for you to switch to the v2 API (which uses the API the Wellbeeing app uses).  Since i don't count on the old API being available for a long time in the future, i switched my efforts to the newer one.

I added an overview which API has which functionality implemented currently:
https://github.com/Phype/purei9_unofficial/blob/master/functions.md

The interface _should_ be exactly the same, just using another class, but there may be some bugs. Also, the Authentication is a bit more complicated - while you can login via the same username and password to get an access token, the API doesn't like it when you do it too often, so i would propose you try to save the accesstoken and reuse it.

**Comment by Ekman** [comment]
Thanks for the heads up! As soon as I find some time this will definitely be the first thing on my list.

**Comment by Ekman** [comment]
Thanks for the PR.

I'm just going to test this personally for a day or two. Then I'll tag it and make a release out of it.
