### ISSUE TITLE
Local mode

### ISSUE THREAD

**Issue by Phype** [Ekman/home-assistant-pure-i9#28]
I just tested something: When you turn the robot around, you can set the localpw for the local connection without breaking the connection to the cloud. This means that it is pretty easy to make use of the local mode of purei9_unofficial. Users have just turn the robot around and run a command (Maybe this cloud even be included in the home assistant intergration).

As the official app isn't using the local interface anymore anyway, i don't think it breaks anything if we set the localpw to another value as it was before.

So i though maybe it makes sense to kind of include this in the integration. Something like supporting both modes of controlling the robot, depending on what it currently available or something.

What do you think?

**Comment by Ekman** [comment]
Thanks for the suggestion, I appreciate it!

I'd suggest you talk to the guys over at [anhaehne/homeassistant_electrolux_purei9](https://github.com/anhaehne/homeassistant_electrolux_purei9) regarding this. They've created a Home Assistant library for offline Purei9.

This change would either mean a breaking change in the API facing the users of this library or a configuration value, both which I'm not entirely fond of. When I create software I tend to keep them as simple as possible with just the bare necessary configuration. It's easy to create a "one-solution-fits-all" which is not very fun to maintain. In this case, we have a separate integration that could benefit from this instead.

I have so much more things that I'd rather focus on regarding this library. I'll be closing this
