### ISSUE TITLE
Dustbin state

### ISSUE THREAD

**Issue by techillin** [Ekman/home-assistant-pure-i9#29]
**Dustbin state is now implemented in purei9_unofficial**, would be nice if it would be implmented here as Error or an Attribute.

**Comment by techillin** [comment]
https://github.com/Phype/purei9_unofficial/blob/3e7446004d91df5db444a926bc430bb7554a8b0c/src/purei9_unofficial/common.py#L56

**Comment by Ekman** [comment]
Thanks for the suggestion and the link. I'll look into it.

**Comment by Ekman** [comment]
Checklist:

1. [] Update `purei9_unofficial` to version `0.0.8`
2. [] Implement dustbin state

**Comment by Ekman** [comment]
Released as [1.2.0](https://github.com/Ekman/home-assistant-pure-i9/releases/tag/1.2.0)
