### ISSUE TITLE
Proposal for enhanced features

### ISSUE THREAD

**Issue by GitPetri** [Ekman/home-assistant-pure-i9#4]
Thank you for the good work creating this integration.
Looking at this integration after installation and [Vacuum card](https://github.com/denysdovhan/vacuum-card) I couldn't make the following to work, might just be stupid me but if these are not implemented please do consider the following:
- Cleaning area
- Cleaning time
- Maps/zones

Looking at the Android Wellbeing app and [this issue](https://github.com/Phype/purei9_unofficial/issues/8), the data probably is available via the API.

**Comment by Ekman** [comment]
It's always appreciating when people are using your own software 🙇 

That card looks awesome! I'll try and fiddle a little bit with it as well. However, the integration currently does not report any attributes, which that card is using to display various stats. [As soon as I'm confident that the current code is stable](https://github.com/Ekman/home-assistant-pure-i9/issues/5), I'll start looking at adding some attributes.

Also, I'd like to look at adding map functionality. [According to the Home Assistant documentation](https://developers.home-assistant.io/docs/core/entity/vacuum/), a vacuum is able to report `SUPPORT_MAP` as a feature, but I haven't been able to find any documentation on how. Help finding the proper documentation or reference implementation is much appreciated.

**Comment by GitPetri** [comment]
There is at least [this](https://community.home-assistant.io/t/add-map-to-xiaomi-vacuum-cleaner/33155) having links for map fetch for Xiaomi, Rockrobo and [https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)

**Comment by GitPetri** [comment]
https://community.purei9.com/discussion/747/tips-for-saving-a-floor-map

**Comment by drgreenbaum** [comment]
Hi! Great work! Can you add the option to do a spot cleaning too? Seems to be implemented in Home Assistant!

**Comment by Ekman** [comment]
Thank you @drgreenbaum . I'll see what I can do but it'll be a while before I get there.

**Comment by Ekman** [comment]
Thank you @GitPetri for the links. I think I've managed to figure out how maps works in Home Assistant now. Now I just need to try it out and fiddle with it.

**Comment by Ekman** [comment]
I've created separate issues for each request.
