### ISSUE TITLE
My robot wont charge after cleaning

### ISSUE THREAD

**Issue by tanitoo2** [Ekman/home-assistant-pure-i9#53]
Good morning everyone, im having an issue that appear from nowhere.. suddenly the robot needs to charge after 70% of cleaning all the house it will say going for charger and will resume after charging but the robot wont charge at all, the simbol in the APP electrolux just says battery "mid" and theres no
Charging simbol on the app, on the robot (says that is charging) but then an aural alert from the robot "im having problems charging" , tested the batteries with multimiter it says they are good 7.6 volts idk what could
Be the problem, everything works EXCEPT that when it drains the battery "pauses for charging"
It wont go vaccum again and the god damn red simbol
Will appear after a while. I want
To destroy this damn robot

**Comment by tanitoo2** [comment]
I think is a firmware related issue, can someone help me
Please ?

**Comment by Ekman** [comment]
Hey there! You've reached a fan community project for the Pure i9 robots. I'm not affiliated with or endorsed by Electrolux in any way. This is code for the Home Assistant integration and not for the robot firmware.

I suggest you reach out to Electrolux support via [electrolux.com](https://electrolux.com), and they should be able to assist you further.

Good luck!
