### ISSUE TITLE
View and set eco/power mode

### ISSUE THREAD

**Issue by Ekman** [Ekman/home-assistant-pure-i9#7]
Add the ability to view, and set, which power mode is currently active.

**Comment by Ekman** [comment]
Dependent on: https://github.com/Phype/purei9_unofficial/pull/9

**Comment by Phype** [comment]
See https://github.com/Ekman/home-assistant-pure-i9/issues/7

**Comment by Ekman** [comment]
Finishing polishment in #31 . Released as version [1.1.0](https://github.com/Ekman/home-assistant-pure-i9/releases/tag/1.1.0).
