### ISSUE TITLE
class custom_components will be deprecated

### ISSUE THREAD

**Issue by bastiusz** [Ekman/home-assistant-pure-i9#71]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1607
First occurred: 20:41:30 (1 occurrences)
Last logged: 20:41:30

Entity None (<class 'custom_components.purei9.vacuum.PureI9'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.PAUSE|STOP|RETURN_HOME|FAN_SPEED|BATTERY|SEND_COMMAND|STATE|START: 12668>, please create a bug report at https://github.com/Ekman/home-assistant-pure-i9/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by Ekman** [comment]
Thank you for bringing this to my attention.

**Comment by Ekman** [comment]
Fixed. Will be released in next version. I'll let you know.

**Comment by Ekman** [comment]
Released in [2.0.1-rc.2](https://github.com/Ekman/home-assistant-pure-i9/releases/tag/2.0.1-rc.2).
