### ISSUE TITLE
Giving up due to no left retries. Wrong credentials?

### ISSUE THREAD

**Issue by git-damien** [Ekman/home-assistant-pure-i9#73]
Since the beginning of August my Pure i9 has not been unavailable in HA.

In the logs I get:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate

Nothing has changed in my system to cause an authentication issue.
In case it was on the account side I deleted my account and created a new one with matching username and password. No change.

I tried removing and reinstalling the integration but it won't authenticate during the install.

I have restored to a backup in a state where the integration was working, but still have the same problem.

**Comment by techillin** [comment]
https://github.com/Phype/purei9_unofficial/issues/28

**Comment by git-damien** [comment]
Thanks for looking at the issue. But i'm not sure what that means.
Is that a previous ticket with the same problem so I can sit back and wait for it to be fixed because you're on it?

**Comment by Phype** [comment]
Yes, i have the same problem, but I'll not be able to fix it for the next 2 weeks. Another home assistant integration has experienced the same and there is now an official Electrolux API available. See:
 - https://github.com/JohNan/pyelectroluxgroup
 - https://github.com/JohNan/homeassistant-wellbeing/issues/98#issuecomment-2269312879

It might make sense to merge development efforts of this integration or purei9_unofficial with those 2 github projects.

**Comment by JohNan** [comment]
Thanks for referencing to my library @Phype and I like the idea to combine these integrations. Feel free to open up pull requests


I have just pushed a rough first version of it. https://pypi.org/project/pyelectroluxgroup/0.1.0/

Try it out and open an issues or a pull request at the repository if any changes is needed.

**Comment by derkrasseleo** [comment]
Can confirm I have the same issue

**Comment by HonkStonk** [comment]
Got the exact same thing since beginning of Aug. Is the plan to use parts of "pyelectroluxgroup" in this integration later on? The Pure i9 integration has been great to use and really the only simple working alternative so far... Thanks!

**Comment by Ekman** [comment]
Hi. I can't say exactly when I'll have the time to look into this. I'm still using two Electrolux Pure i9s so I'm definitely interested in getting this up and running asap.

**Comment by lorenzo-deluca** [comment]
same issue :/

**Comment by dontbx** [comment]
Electrolux wrote the following:

"We regret that the integration of your Pure i9 into your smart home system is no longer working. Your feedback on the API is important to us, and we thank you for your patience. Open and officially available APIs are on the horizon. We hope you will soon be able to establish a seamless connection again!"

We can therefore expect a new API.

**Comment by Ekman** [comment]
> Electrolux wrote the following:
> 
> "We regret that the integration of your Pure i9 into your smart home system is no longer working. Your feedback on the API is important to us, and we thank you for your patience. Open and officially available APIs are on the horizon. We hope you will soon be able to establish a seamless connection again!"
> 
> We can therefore expect a new API.

That's actually great news. Short term, it sucks that the integration doesn't work. Long term, having an official API should ensure that this doesn't happen again.

Anyhow, I'm going to try and solve this short term whenever I have some spare time.

**Comment by p2923260** [comment]
Thanks Niklas, we look forward for an update. If you need any support for test just let us know.

**Comment by p2923260** [comment]
Please let us know about the fix even as beta version.

**Comment by JohNan** [comment]
There's a PR n this repo https://github.com/JohNan/homeassistant-wellbeing/pull/145 to add support for Pure i9. It does not contain all features, but it's a start.

**Comment by Ekman** [comment]
Finally, thanks to the help of @Phype then the integration is working again. Also, thank to the train company for having a couple of hours delay so that I could get some time to look into this.

I've released a test version of the integration `2.0.0-rc.1`, which means I haven't tested it yet BUT you should be able to download it now. I'll test it in the coming days and probably make minor changes to it. Eventually, I'll release a stable `2.0.0`.

I had to bump the major version of the integration, meaning there are backwards incompatible changes. I'll write more about that in the stable release.
